import type { QuizQuestion } from './quizData';

// 200 easy Nigerian-themed quiz questions.
export const easyQuestions: QuizQuestion[] = [
  { id: 'eq1', question: "What is the capital of Lagos State?", options: ["Ikeja", "Lagos Island", "Lekki", "Surulere"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq2', question: "What is the capital of Kano State?", options: ["Kaduna", "Kano", "Sokoto", "Katsina"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq3', question: "What is the capital of Rivers State?", options: ["Yenagoa", "Calabar", "Port Harcourt", "Warri"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq4', question: "What is the capital of Oyo State?", options: ["Ogbomoso", "Iseyin", "Ibadan", "Saki"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq5', question: "What is the capital of Ogun State?", options: ["Ijebu-Ode", "Sagamu", "Ota", "Abeokuta"], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq6', question: "What is the capital of Anambra State?", options: ["Awka", "Onitsha", "Nnewi", "Ekwulobia"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq7', question: "What is the capital of Imo State?", options: ["Aba", "Owerri", "Orlu", "Okigwe"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq8', question: "What is the capital of Edo State?", options: ["Auchi", "Ekpoma", "Benin City", "Uromi"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq9', question: "What is the capital of Delta State?", options: ["Warri", "Sapele", "Ughelli", "Asaba"], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq10', question: "What is the capital of Cross River State?", options: ["Ikom", "Calabar", "Ogoja", "Obudu"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq11', question: "What is the capital of Akwa Ibom State?", options: ["Eket", "Uyo", "Ikot Ekpene", "Oron"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq12', question: "What is the capital of Bayelsa State?", options: ["Brass", "Yenagoa", "Sagbama", "Nembe"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq13', question: "What is the capital of Abia State?", options: ["Aba", "Umuahia", "Arochukwu", "Ohafia"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq14', question: "What is the capital of Ebonyi State?", options: ["Afikpo", "Onueke", "Abakaliki", "Edda"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq15', question: "What is the capital of Enugu State?", options: ["Enugu", "Nsukka", "Awgu", "Oji"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq16', question: "What is the capital of Plateau State?", options: ["Pankshin", "Jos", "Shendam", "Bukuru"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq17', question: "What is the capital of Kaduna State?", options: ["Zaria", "Kafanchan", "Kaduna", "Zonkwa"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq18', question: "What is the capital of Niger State?", options: ["Suleja", "Bida", "Kontagora", "Minna"], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq19', question: "What is the capital of Sokoto State?", options: ["Wurno", "Sokoto", "Tambuwal", "Gwadabawa"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq20', question: "What is the capital of Kebbi State?", options: ["Argungu", "Yauri", "Birnin Kebbi", "Zuru"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq21', question: "What is the capital of Zamfara State?", options: ["Anka", "Gusau", "Tsafe", "Kaura Namoda"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq22', question: "What is the capital of Katsina State?", options: ["Daura", "Funtua", "Katsina", "Dutsin-Ma"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq23', question: "What is the capital of Jigawa State?", options: ["Hadejia", "Dutse", "Gumel", "Birnin Kudu"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq24', question: "What is the capital of Yobe State?", options: ["Potiskum", "Nguru", "Damaturu", "Gashua"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq25', question: "What is the capital of Borno State?", options: ["Bama", "Maiduguri", "Biu", "Konduga"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq26', question: "What is the capital of Adamawa State?", options: ["Mubi", "Numan", "Yola", "Ganye"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq27', question: "What is the capital of Taraba State?", options: ["Wukari", "Jalingo", "Bali", "Gembu"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq28', question: "What is the capital of Gombe State?", options: ["Bajoga", "Kaltungo", "Billiri", "Gombe"], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq29', question: "What is the capital of Bauchi State?", options: ["Misau", "Bauchi", "Azare", "Jamaare"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq30', question: "What is the capital of Nasarawa State?", options: ["Keffi", "Akwanga", "Lafia", "Karu"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq31', question: "What is the capital of Benue State?", options: ["Gboko", "Otukpo", "Makurdi", "Katsina-Ala"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq32', question: "What is the capital of Kogi State?", options: ["Idah", "Okene", "Ankpa", "Lokoja"], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq33', question: "What is the capital of Kwara State?", options: ["Offa", "Ilorin", "Omu-Aran", "Jebba"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq34', question: "What is the capital of Osun State?", options: ["Ife", "Ilesa", "Ede", "Osogbo"], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq35', question: "What is the capital of Ekiti State?", options: ["Ikere", "Ado-Ekiti", "Ijero", "Iyin"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq36', question: "What is the capital of Ondo State?", options: ["Ondo Town", "Owo", "Akure", "Okitipupa"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq37', question: "Which is Nigeria's federal capital?", options: ["Lagos", "Abuja", "Kaduna", "Ibadan"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq38', question: "Which colour is on top of the Nigerian flag?", options: ["Green", "White", "Black", "Red"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq39', question: "How many colours are on the Nigerian flag?", options: ["Two", "Three", "Four", "Five"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq40', question: "What is the national symbol bird of Nigeria?", options: ["Pigeon", "Eagle", "Hawk", "Owl"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq41', question: "Which day is Nigeria's Independence Day?", options: ["October 1", "May 29", "June 12", "January 1"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq42', question: "Who was Nigeria's first President?", options: ["Obasanjo", "Azikiwe", "Shagari", "Babangida"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq43', question: "Which of these is a Nigerian state?", options: ["Accra", "Lagos", "Lome", "Cotonou"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq44', question: "Which of these is NOT a Nigerian state?", options: ["Kano", "Lagos", "Tema", "Sokoto"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq45', question: "The Niger and Benue rivers meet at?", options: ["Onitsha", "Lokoja", "Makurdi", "Yenagoa"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq46', question: "Which is the longest bridge in Nigeria?", options: ["Eko Bridge", "Carter Bridge", "Third Mainland Bridge", "Niger Bridge"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq47', question: "Which is the largest city in Nigeria?", options: ["Abuja", "Kano", "Lagos", "Ibadan"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq48', question: "What is the main airport in Lagos called?", options: ["Nnamdi Azikiwe", "Murtala Muhammed", "Aminu Kano", "Port Harcourt Intl"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq49', question: "What is the main airport in Abuja called?", options: ["Murtala Muhammed", "Nnamdi Azikiwe", "Mallam Aminu Kano", "Sam Mbakwe"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq50', question: "Which Nigerian state is called 'Centre of Excellence'?", options: ["Oyo", "Lagos", "Rivers", "Edo"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq51', question: "Which state is called 'Garden City'? (City)", options: ["Port Harcourt", "Calabar", "Enugu", "Uyo"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq52', question: "Which city is known as 'Coal City'?", options: ["Jos", "Enugu", "Aba", "Onitsha"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq53', question: "Which city is known as 'Tin City'?", options: ["Jos", "Kaduna", "Bauchi", "Minna"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq54', question: "Which Nigerian region produces the most crude oil?", options: ["North", "Niger Delta", "South-West", "Middle Belt"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq55', question: "Which is Nigeria's main currency?", options: ["Cedi", "Naira", "Franc", "Dalasi"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq56', question: "How many local governments does Nigeria have?", options: ["774", "767", "800", "734"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq57', question: "How many states does Nigeria have?", options: ["30", "36", "37", "35"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq58', question: "Which is the smallest state by land area?", options: ["Imo", "Lagos", "Anambra", "Abia"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq59', question: "Which is the largest state by land area?", options: ["Borno", "Kaduna", "Niger", "Taraba"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq60', question: "Aso Rock is found in?", options: ["Lagos", "Abuja", "Kaduna", "Jos"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq61', question: "Olumo Rock is found in?", options: ["Ibadan", "Akure", "Abeokuta", "Ilesa"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq62', question: "Zuma Rock is found in?", options: ["Niger State", "FCT", "Kogi", "Kaduna"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq63', question: "Idanre Hills are in which state?", options: ["Ekiti", "Osun", "Ondo", "Oyo"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq64', question: "Erin-Ijesha Waterfall is in which state?", options: ["Osun", "Ondo", "Ekiti", "Oyo"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq65', question: "Yankari Game Reserve is in which state?", options: ["Plateau", "Bauchi", "Gombe", "Taraba"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq66', question: "Obudu Mountain Resort is in which state?", options: ["Cross River", "Akwa Ibom", "Ebonyi", "Benue"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq67', question: "Lekki is located in which state?", options: ["Ogun", "Lagos", "Oyo", "Osun"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq68', question: "Ikoyi is located in which state?", options: ["Lagos", "Ogun", "Rivers", "Edo"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq69', question: "Victoria Island is located in?", options: ["Abuja", "Lagos", "Port Harcourt", "Calabar"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq70', question: "Eko Atlantic City is in?", options: ["Abuja", "Calabar", "Lagos", "Lekki Free Zone"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq71', question: "Banana Island is in?", options: ["Lagos", "Abuja", "Bayelsa", "Akwa Ibom"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq72', question: "Apapa is famous for?", options: ["Beaches", "Seaport", "Mountains", "Markets"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq73', question: "Tin Can Island is in?", options: ["Port Harcourt", "Lagos", "Warri", "Calabar"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq74', question: "Onne Port is in?", options: ["Lagos", "Rivers", "Delta", "Akwa Ibom"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq75', question: "Which state is bordered by the Atlantic Ocean?", options: ["Kano", "Lagos", "Plateau", "Sokoto"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq76', question: "Which is the official language of Nigeria?", options: ["French", "English", "Hausa", "Yoruba"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq77', question: "Which language is widely spoken in the South-East?", options: ["Yoruba", "Hausa", "Igbo", "Edo"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq78', question: "Which language is widely spoken in the North?", options: ["Igbo", "Yoruba", "Hausa", "Tiv"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq79', question: "Which language is widely spoken in the South-West?", options: ["Igbo", "Hausa", "Edo", "Yoruba"], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq80', question: "How many geo-political zones are in Nigeria?", options: ["Five", "Six", "Seven", "Four"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq81', question: "Which zone is Lagos in?", options: ["South-East", "South-South", "South-West", "North-Central"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq82', question: "Which zone is Abuja (FCT) in?", options: ["North-Central", "North-East", "South-West", "North-West"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq83', question: "Which zone is Enugu in?", options: ["South-East", "South-South", "North-Central", "South-West"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq84', question: "Which zone is Rivers in?", options: ["South-East", "South-South", "South-West", "North-Central"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq85', question: "Which zone is Kano in?", options: ["North-East", "North-Central", "North-West", "South-West"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq86', question: "Which zone is Borno in?", options: ["North-Central", "North-West", "North-East", "South-South"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq87', question: "Which highway connects Lagos to Ibadan?", options: ["Lagos-Ibadan Expressway", "Third Mainland", "Eko Bridge", "Lekki Coastal Road"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq88', question: "Which expressway leads to Abuja from Kaduna?", options: ["Kaduna-Abuja Expressway", "Trans-Sahara", "East-West", "Lokoja-Abuja"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq89', question: "Which Nigerian river is shared with Cameroon?", options: ["Niger", "Benue", "Ogun", "Kaduna"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq90', question: "Lake Chad is in which part of Nigeria?", options: ["South", "East", "North-East", "North-West"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq91', question: "Which Nigerian state borders Lake Chad?", options: ["Yobe", "Borno", "Adamawa", "Jigawa"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq92', question: "Which country borders Nigeria to the east?", options: ["Niger", "Benin", "Chad", "Cameroon"], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq93', question: "Which country borders Nigeria to the west?", options: ["Niger", "Cameroon", "Benin", "Togo"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq94', question: "Which country borders Nigeria to the north?", options: ["Niger", "Mali", "Chad", "Burkina Faso"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq95', question: "Which water body is to the south of Nigeria?", options: ["Mediterranean Sea", "Atlantic Ocean", "Indian Ocean", "Red Sea"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq96', question: "How many regions did Nigeria have at independence?", options: ["Two", "Three", "Four", "Five"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq97', question: "Who designed the Nigerian flag?", options: ["Tafawa Balewa", "Akinkunmi", "Awolowo", "Azikiwe"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq98', question: "Which state is called 'Gateway State'?", options: ["Ogun", "Oyo", "Lagos", "Osun"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq99', question: "Which state is called 'Pacesetter State'?", options: ["Lagos", "Oyo", "Ogun", "Osun"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq100', question: "Which state is called 'Sunshine State'?", options: ["Ekiti", "Osun", "Ondo", "Edo"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq101', question: "Which state is called 'Land of Hospitality'?", options: ["Cross River", "Plateau", "Akwa Ibom", "Bayelsa"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq102', question: "Which state is called 'Salt of the Nation'?", options: ["Akwa Ibom", "Ebonyi", "Bayelsa", "Cross River"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq103', question: "Which state is called 'Treasure Base of the Nation'?", options: ["Akwa Ibom", "Rivers", "Bayelsa", "Delta"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq104', question: "Which state is 'Land of Promise'?", options: ["Akwa Ibom", "Cross River", "Bayelsa", "Edo"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq105', question: "Which state is 'Fountain of Knowledge'?", options: ["Kwara", "Osun", "Oyo", "Ondo"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq106', question: "Which state is 'Food Basket of the Nation'?", options: ["Plateau", "Benue", "Niger", "Kogi"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq107', question: "Which state is 'Confluence State'?", options: ["Niger", "Kogi", "Kwara", "Benue"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq108', question: "Which state is 'Home of Peace and Tourism'?", options: ["Plateau", "Cross River", "Bayelsa", "Akwa Ibom"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq109', question: "Which state is 'Big Heart of Nigeria'?", options: ["Adamawa", "Taraba", "Gombe", "Yobe"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq110', question: "Which state is 'Pearl of Tourism'?", options: ["Plateau", "Cross River", "Akwa Ibom", "Ondo"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq111', question: "Which state is 'Heart of the Nation'?", options: ["FCT", "Kogi", "Niger", "Plateau"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq112', question: "Which state is 'Centre of Commerce'?", options: ["Lagos", "Onitsha", "Aba", "Anambra"], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq113', question: "Which is Nigeria's biggest market traditionally?", options: ["Mile 12", "Onitsha Main Market", "Ariaria", "Balogun"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq114', question: "Mile 12 Market is in?", options: ["Lagos", "Ogun", "Oyo", "Edo"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq115', question: "Ariaria Market is in?", options: ["Aba", "Owerri", "Onitsha", "Enugu"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq116', question: "Wuse Market is in?", options: ["Lagos", "Abuja", "Kano", "Kaduna"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq117', question: "Sabon Gari Market is in?", options: ["Kaduna", "Jos", "Kano", "Sokoto"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq118', question: "Balogun Market is in?", options: ["Ibadan", "Lagos", "Abeokuta", "Ilorin"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq119', question: "Computer Village is in?", options: ["Surulere", "Ikeja", "Yaba", "Lekki"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq120', question: "Yaba is famous for?", options: ["Beaches", "Tech & fashion", "Mountains", "Farming"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq121', question: "Festac Town is in which state?", options: ["Lagos", "Ogun", "Edo", "Rivers"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq122', question: "Surulere is on which side of Lagos?", options: ["Island", "Mainland", "Lekki", "Eko Atlantic"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq123', question: "Which bridge connects Lagos Island to Ikoyi?", options: ["Carter", "Eko", "Falomo", "Third Mainland"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq124', question: "Which bridge connects Lekki to Ikoyi?", options: ["Lekki-Ikoyi Link Bridge", "Carter", "Eko", "Falomo"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq125', question: "Which is the oldest university in Nigeria?", options: ["UNILAG", "UI", "ABU", "UNN"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq126', question: "UNILAG is in which state?", options: ["Ogun", "Lagos", "Oyo", "Edo"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq127', question: "OAU is in which town?", options: ["Ibadan", "Ile-Ife", "Ado-Ekiti", "Akure"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq128', question: "UNN is located in?", options: ["Enugu", "Nsukka", "Awka", "Owerri"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq129', question: "ABU Zaria is in which state?", options: ["Kano", "Kaduna", "Katsina", "Sokoto"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq130', question: "UNIBEN is in which city?", options: ["Auchi", "Ekpoma", "Benin City", "Sapele"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq131', question: "UNIPORT is in which state?", options: ["Bayelsa", "Rivers", "Akwa Ibom", "Delta"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq132', question: "Which day is Democracy Day in Nigeria?", options: ["October 1", "May 29", "June 12", "July 4"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq133', question: "Workers' Day in Nigeria is?", options: ["May 1", "May 5", "June 1", "April 1"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq134', question: "Children's Day in Nigeria is?", options: ["May 27", "May 30", "June 1", "April 27"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq135', question: "Eyo Festival is celebrated in?", options: ["Calabar", "Lagos", "Abeokuta", "Ibadan"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq136', question: "Argungu Fishing Festival is in?", options: ["Sokoto", "Kebbi", "Zamfara", "Niger"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq137', question: "Durbar Festival is famous in?", options: ["Kano", "Lagos", "Ibadan", "Enugu"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq138', question: "Carnival Calabar holds in?", options: ["Lagos", "Calabar", "Port Harcourt", "Uyo"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq139', question: "New Yam Festival is celebrated mainly by?", options: ["Hausa", "Yoruba", "Igbo", "Ijaw"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq140', question: "Osun-Osogbo Festival is in?", options: ["Oyo", "Osun", "Ondo", "Ekiti"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq141', question: "Which is Nigeria's national anthem opening line?", options: ["Arise O Compatriots", "God bless our nation", "Nigeria we hail thee", "Land of our birth"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq142', question: "Which Nigerian state has the highest mountain?", options: ["Plateau", "Taraba", "Adamawa", "Cross River"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq143', question: "Chappal Waddi mountain is in?", options: ["Plateau", "Taraba", "Adamawa", "Bauchi"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq144', question: "Which is Nigeria's biggest stadium (capacity)?", options: ["Teslim Balogun", "MKO Abiola Stadium Abuja", "Liberty Stadium", "Sani Abacha"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq145', question: "National Stadium Surulere is in?", options: ["Lagos", "Abuja", "Ibadan", "Kaduna"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq146', question: "National Mosque is in?", options: ["Kano", "Lagos", "Abuja", "Sokoto"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq147', question: "National Christian Centre is in?", options: ["Lagos", "Abuja", "Enugu", "Calabar"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq148', question: "Eagle Square is in?", options: ["Lagos", "Abuja", "Kaduna", "Jos"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq149', question: "National Theatre is in?", options: ["Lagos", "Abuja", "Ibadan", "Enugu"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq150', question: "Tafawa Balewa Square is in?", options: ["Abuja", "Lagos", "Kaduna", "Bauchi"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq151', question: "Which Nigerian city hosts the National Assembly?", options: ["Lagos", "Abuja", "Kaduna", "Enugu"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq152', question: "Aso Villa is the residence of the?", options: ["Vice President", "President", "Senate President", "Chief Justice"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq153', question: "Which state has Ikogosi Warm Springs?", options: ["Ondo", "Ekiti", "Osun", "Edo"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq154', question: "Which state has Awhum Waterfall?", options: ["Anambra", "Enugu", "Imo", "Ebonyi"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq155', question: "Which state has Ngwo Cave?", options: ["Enugu", "Anambra", "Abia", "Imo"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq156', question: "Ogbunike Caves are in which state?", options: ["Enugu", "Anambra", "Imo", "Abia"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq157', question: "Which state has Gurara Falls?", options: ["Niger", "Kaduna", "FCT", "Kogi"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq158', question: "Which state has Farin Ruwa Falls?", options: ["Plateau", "Nasarawa", "Bauchi", "Kaduna"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq159', question: "Mambilla Plateau is in?", options: ["Plateau", "Adamawa", "Taraba", "Gombe"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq160', question: "Which is Nigeria's largest seaport?", options: ["Onne", "Apapa", "Tin Can", "Calabar"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq161', question: "Which Nigerian state has the most Atlantic coastline?", options: ["Lagos", "Ondo", "Bayelsa", "Delta"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq162', question: "Which state has the longest Nigerian coastline?", options: ["Lagos", "Bayelsa", "Ondo", "Akwa Ibom"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq163', question: "Bonny Island is in?", options: ["Bayelsa", "Rivers", "Akwa Ibom", "Delta"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq164', question: "Forcados is in?", options: ["Edo", "Delta", "Bayelsa", "Rivers"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq165', question: "Escravos is in?", options: ["Delta", "Bayelsa", "Rivers", "Edo"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq166', question: "Brass terminal is in?", options: ["Bayelsa", "Rivers", "Delta", "Akwa Ibom"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq167', question: "Which is the largest island in Lagos?", options: ["Victoria Island", "Lagos Island", "Banana Island", "Snake Island"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq168', question: "Ojo Cantonment is in?", options: ["Abuja", "Lagos", "Kaduna", "Jos"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq169', question: "Defence Headquarters is in?", options: ["Lagos", "Abuja", "Kaduna", "Minna"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq170', question: "Naval Headquarters is in?", options: ["Lagos", "Abuja", "Calabar", "PH"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq171', question: "Police HQ Force is in?", options: ["Lagos", "Abuja", "Kaduna", "Enugu"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq172', question: "Which is Nigeria's biggest refinery location?", options: ["Warri", "Kaduna", "Port Harcourt", "Lagos"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq173', question: "Dangote Refinery is in?", options: ["Ogun", "Lagos", "Rivers", "Delta"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq174', question: "Lekki Free Trade Zone is in?", options: ["Lagos", "Ogun", "Edo", "Rivers"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq175', question: "Tinapa Resort is in?", options: ["Cross River", "Akwa Ibom", "Bayelsa", "Edo"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq176', question: "Which state is famous for Akara and Eko?", options: ["Lagos", "Ogun", "Osun", "Oyo"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq177', question: "Suya is most associated with which region?", options: ["South", "West", "North", "East"], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq178', question: "Which Nigerian dish uses cassava flakes?", options: ["Tuwo", "Garri", "Amala", "Eba"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq179', question: "Amala is from which ethnic group?", options: ["Igbo", "Yoruba", "Hausa", "Edo"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq180', question: "Tuwo Shinkafa is from which region?", options: ["South", "North", "West", "East"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq181', question: "Banga soup originates from?", options: ["Yoruba", "Itsekiri/Urhobo", "Hausa", "Igbo"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq182', question: "Egusi soup is made from?", options: ["Beans", "Melon seeds", "Yam", "Cassava"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq183', question: "Jollof Rice is most famous in?", options: ["East Africa", "West Africa", "Central Africa", "North Africa"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq184', question: "Which animal appears on Nigeria's coat of arms?", options: ["Lion", "Eagle", "Horse", "Two horses"], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq185', question: "What does the green colour on Nigerian flag stand for?", options: ["Peace", "Agriculture", "Wealth", "Unity"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq186', question: "What does the white colour on Nigerian flag stand for?", options: ["Wealth", "Peace", "Unity", "Power"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq187', question: "Which is Nigeria's biggest export?", options: ["Cocoa", "Crude oil", "Gold", "Rubber"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq188', question: "Cocoa is most produced in?", options: ["South-East", "South-West", "North-East", "South-South"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq189', question: "Groundnut pyramids were famous in?", options: ["Lagos", "Kano", "Ibadan", "Jos"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq190', question: "Tin mining is famous in?", options: ["Jos", "Kano", "Lagos", "Sokoto"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq191', question: "Which mineral is mined in Enugu?", options: ["Coal", "Tin", "Gold", "Lead"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq192', question: "Which mineral is mined in Itakpe?", options: ["Coal", "Iron ore", "Gold", "Bauxite"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq193', question: "Itakpe is in which state?", options: ["Kaduna", "Kogi", "Niger", "FCT"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq194', question: "Which Nigerian dam is on the Niger?", options: ["Shiroro", "Kainji", "Jebba", "All of these"], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq195', question: "Kainji Dam is in?", options: ["Niger State", "Kebbi", "Kwara", "Kogi"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq196', question: "Shiroro Dam is in?", options: ["Niger State", "Kaduna", "FCT", "Kogi"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq197', question: "Jebba Dam straddles?", options: ["Kwara & Niger", "Kogi & FCT", "Niger & Kebbi", "Sokoto"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq198', question: "Which power plant is gas-fired in Lagos?", options: ["Egbin", "Kainji", "Shiroro", "Jebba"], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq199', question: "Which is Nigeria's biggest gas plant location?", options: ["Bonny", "Escravos", "Forcados", "All of these"], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'eq200', question: "PHCN was renamed to?", options: ["NEPA", "GENCOs/DISCOs", "TCN", "All of these"], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
];
