import type { QuizQuestion } from './quizData';

export const extraKnowledgeQuestions2: QuizQuestion[] = [
  { id: 'ke3001', question: 'Amala is a traditional food of which ethnic group?', options: ['Igbo', 'Hausa', 'Yoruba', 'Ijaw'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3002', question: 'Suya is a popular Nigerian street food made from?', options: ['Fish', 'Grilled skewered meat', 'Chicken only', 'Vegetables'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3003', question: 'Jollof rice is most associated with which cuisine?', options: ['West African', 'Asian', 'European', 'South African'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3004', question: 'Pounded yam is typically eaten with?', options: ['Bread', 'Salad', 'Soup/stew', 'Rice'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3005', question: 'Egusi soup is made primarily from?', options: ['Fish', 'Melon seeds', 'Tomatoes', 'Beans'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3006', question: 'Tuwo Shinkafa is a staple food from which region?', options: ['South-West', 'North', 'South-East', 'South-South'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3007', question: 'Chin chin is a Nigerian?', options: ['Soup', 'Drink', 'Stew', 'Snack/fried pastry'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3008', question: 'Kilishi is the Nigerian version of what?', options: ['Bread', 'Jerky/dried meat', 'Soup', 'Drink'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3009', question: 'Ofada rice is grown primarily in which state?', options: ['Ogun', 'Lagos', 'Kano', 'Benue'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3010', question: 'The main ingredient in Ogbono soup is?', options: ['Palm fruit', 'Groundnuts', 'Bush mango seeds', 'Cocoyam'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3011', question: 'Nkwobi is a delicacy from which ethnic group?', options: ['Yoruba', 'Igbo', 'Hausa', 'Fulani'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'ke3012', question: 'Masa is a rice cake popular in which region?', options: ['South-West', 'South-East', 'South-South', 'North'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3013', question: 'Pepper soup is typically served in?', options: ['Plates', 'Boxes', 'Bags', 'Bowls/calabash'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3014', question: 'Akara is made from?', options: ['Rice', 'Beans', 'Corn', 'Wheat'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3015', question: 'Moi Moi is a steamed?', options: ['Rice pudding', 'Yam pudding', 'Bean pudding', 'Corn pudding'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3016', question: 'Boli is made from?', options: ['Plantain', 'Yam', 'Cassava', 'Potato'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3017', question: 'Efo Riro is a type of?', options: ['Meat dish', 'Vegetable soup', 'Rice dish', 'Snack'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3018', question: 'Kunun Gyada is a drink made from?', options: ['Millet', 'Sorghum', 'Corn', 'Groundnuts and rice'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3019', question: 'Fura da Nono is a dairy drink from which group?', options: ['Fulani', 'Igbo', 'Yoruba', 'Ijaw'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'ke3020', question: 'Ewedu soup is popular in which part of Nigeria?', options: ['South-West', 'North', 'South-East', 'South-South'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3021', question: 'Palm wine is tapped from which tree?', options: ['Coconut', 'Banana tree', 'Palm tree', 'Mango tree'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3022', question: 'Abacha (African salad) is from which ethnic group?', options: ['Yoruba', 'Hausa', 'Igbo', 'Tiv'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3023', question: 'Zobo drink is made from?', options: ['Ginger', 'Orange', 'Lemon', 'Hibiscus flower'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3024', question: 'Dodo is another name for?', options: ['Fried yam', 'Fried plantain', 'Fried fish', 'Fried chicken'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3025', question: 'Gbegiri soup is made from?', options: ['Melon', 'Corn', 'Beans', 'Groundnut'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'ke3026', question: 'The National Assembly Complex is in which city?', options: ['Lagos', 'Abuja', 'Kaduna', 'Ibadan'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3027', question: 'Shoprite first entered Nigeria through which city?', options: ['Lagos', 'Abuja', 'Port Harcourt', 'Kano'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'ke3028', question: 'The Nigerian Stock Exchange is headquartered in?', options: ['Lagos', 'Abuja', 'Kaduna', 'Port Harcourt'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3029', question: 'The Obasanjo Presidential Library is in which state?', options: ['Ogun', 'Lagos', 'Oyo', 'Abuja FCT'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'ke3030', question: 'Computer Village in Lagos is located in which area?', options: ['Surulere', 'Ikeja', 'Lekki', 'Victoria Island'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3031', question: 'The National Stadium (Surulere) is in which city?', options: ['Lagos', 'Abuja', 'Ibadan', 'Benin'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3032', question: 'Olusegun Obasanjo is from which state?', options: ['Lagos', 'Oyo', 'Osun', 'Ogun'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3033', question: 'Which Nigerian airport has the IATA code LOS?', options: ['Lagos', 'Abuja', 'Kano', 'Port Harcourt'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'kh3034', question: 'The first storey building in Nigeria is in which city?', options: ['Lagos', 'Calabar', 'Badagry', 'Ibadan'], correctAnswer: 2, category: 'knowledge', difficulty: 'hard' },
  { id: 'ke3035', question: 'Idumota Market is located in which part of Lagos?', options: ['Lagos Island', 'Lekki', 'Ikeja', 'Surulere'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3036', question: 'The National Museum Lagos is located on which street?', options: ['King George V Road', 'Broad Street', 'Awolowo Road', 'Marina'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'kh3037', question: 'The largest church building in Nigeria is in which state?', options: ['Rivers', 'Ogun', 'Lagos', 'Akwa Ibom'], correctAnswer: 2, category: 'knowledge', difficulty: 'hard' },
  { id: 'km3038', question: 'Oriental Hotel Lagos is located in which area?', options: ['Ikeja', 'Victoria Island', 'Lekki', 'Ikoyi'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3039', question: 'The Lagos Blue Line rail runs from Marina to?', options: ['Mile 2', 'Ikeja', 'Oshodi', 'Epe'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'ke3040', question: 'Tejuosho Market is in which area of Lagos?', options: ['Surulere', 'Ikeja', 'Mushin', 'Yaba'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3041', question: 'The Palms Shopping Mall Lagos is in which area?', options: ['Ikeja', 'Victoria Island', 'Lekki', 'Surulere'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3042', question: 'Landmark Beach is located in which area?', options: ['Ikoyi', 'Oniru', 'Victoria Island', 'Lekki Phase 1'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3043', question: 'The MMIA domestic terminal serves which city?', options: ['Abuja', 'Kano', 'Lagos', 'Port Harcourt'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3044', question: 'Silverbird Galleria Lagos is on which road?', options: ['Lekki-Epe', 'Adeola Odeku', 'Admiralty Way', 'Ozumba Mbadiwe'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3045', question: 'The Nike Art Gallery is in which area of Lagos?', options: ['Ikoyi', 'Surulere', 'Ikeja', 'Lekki'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3046', question: 'Alaba International Market specializes in?', options: ['Food', 'Electronics', 'Clothing', 'Vehicles'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3047', question: 'Terra Kulture is a cultural center in which city?', options: ['Abuja', 'Ibadan', 'Lagos', 'Calabar'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'ke3048', question: 'Eko Hotel is located on which island?', options: ['Lagos Island', 'Banana Island', 'Ikoyi', 'Victoria Island'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3049', question: 'The Civic Centre Lagos is on which road?', options: ['Marina', 'Ahmadu Bello Way', 'Ozumba Mbadiwe', 'Broad Street'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'ke3050', question: 'Ikeja City Mall (ICM) is near which landmark?', options: ['University', 'Stadium', 'Airport', 'Hospital'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3051', question: 'How many local government areas does Nigeria have?', options: ['574', '774', '674', '874'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3052', question: 'Which Nigerian state borders Cameroon to the east?', options: ['Borno', 'Adamawa', 'All of the above', 'Cross River'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3053', question: 'The Sahel savanna is found in which part of Nigeria?', options: ['South', 'East', 'Far North', 'West'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3054', question: 'Which Nigerian state is landlocked but closest to the coast?', options: ['Ekiti', 'Oyo', 'Osun', 'Ogun'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'kh3055', question: 'The Guinea Savanna covers approximately what percentage of Nigeria?', options: ['20%', '50%', '30%', '70%'], correctAnswer: 1, category: 'knowledge', difficulty: 'hard' },
  { id: 'kh3056', question: 'Nigeria\'s coordinates are approximately?', options: ['10-20\u00b0N, 10-20\u00b0E', '0-10\u00b0N, 0-10\u00b0E', '5-14\u00b0N, 3-14\u00b0E', '5-14\u00b0S, 3-14\u00b0W'], correctAnswer: 2, category: 'knowledge', difficulty: 'hard' },
  { id: 'kh3057', question: 'Which Nigerian river is a tributary of the Benue?', options: ['Ogun River', 'Donga River', 'Osun River', 'Cross River'], correctAnswer: 1, category: 'knowledge', difficulty: 'hard' },
  { id: 'ke3058', question: 'The mangrove swamp is found in which zone?', options: ['Coastal/Southern Nigeria', 'Northern Nigeria', 'Central Nigeria', 'Western Nigeria'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3059', question: 'Which Nigerian state has the most rivers?', options: ['Lagos', 'Delta', 'Rivers', 'Cross River'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'kh3060', question: 'The Jos Plateau is approximately how many meters above sea level?', options: ['1200m', '1000m', '500m', '1800m'], correctAnswer: 0, category: 'knowledge', difficulty: 'hard' },
  { id: 'km3061', question: 'Which vegetation zone has the baobab tree?', options: ['Sudan savanna', 'Swamp forest', 'Rainforest', 'Mangrove'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'ke3062', question: 'The Bight of Benin is part of which ocean?', options: ['Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Arctic Ocean'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'kh3063', question: 'Mount Patti is located in which state?', options: ['Niger', 'Kogi', 'Kwara', 'Plateau'], correctAnswer: 1, category: 'knowledge', difficulty: 'hard' },
  { id: 'km3064', question: 'The freshwater swamp forest is found in which Nigerian state?', options: ['Lagos', 'Rivers', 'Kano', 'Kaduna'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'kh3065', question: 'Which Nigerian state has the Gashaka-Gumti National Park?', options: ['Adamawa', 'Taraba', 'Bauchi', 'Plateau'], correctAnswer: 1, category: 'knowledge', difficulty: 'hard' },
  { id: 'km3066', question: 'Lake Kainji is in which state?', options: ['Sokoto', 'Kwara', 'Kebbi', 'Niger'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3067', question: 'The lowest point in Nigeria is along?', options: ['Lake Chad', 'River Niger', 'The coast', 'River Benue'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'ke3068', question: 'Which season in Nigeria lasts from November to March?', options: ['Both B and C', 'Dry season', 'Harmattan', 'Rainy season'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'kh3069', question: 'The tropical rainforest zone receives approximately how much rainfall?', options: ['2000mm+', '1000mm', '500mm', '3000mm+'], correctAnswer: 0, category: 'knowledge', difficulty: 'hard' },
  { id: 'kh3070', question: 'Which Nigerian state is entirely in the montane zone?', options: ['Plateau', 'Taraba', 'Adamawa', 'None entirely'], correctAnswer: 3, category: 'knowledge', difficulty: 'hard' },
  { id: 'ke3071', question: 'The Igbo masquerade is called?', options: ['Mmanwu', 'Egungun', 'Eyo', 'Gelede'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'kh3072', question: 'The Yoruba New Year festival is called?', options: ['Olojo', 'Eyo', 'Ileya', 'Odun Oba'], correctAnswer: 0, category: 'knowledge', difficulty: 'hard' },
  { id: 'ke3073', question: 'Which Nigerian festival involves horse riding?', options: ['Eyo', 'New Yam', 'Durbar', 'Osun-Osogbo'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3074', question: 'The traditional Yoruba greeting involves?', options: ['Handshake', 'Waving', 'Bowing', 'Prostration/kneeling'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3075', question: 'Nollywood is Nigeria"s?', options: ['Music industry', 'Film industry', 'Fashion industry', 'Tech industry'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3076', question: 'The Hausa traditional cap is called?', options: ['Fila', 'Agbada', 'Fez', 'Fula'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3077', question: 'Adire is a traditional fabric from which group?', options: ['Yoruba', 'Igbo', 'Hausa', 'Edo'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3078', question: 'The Igbo traditional title for a wealthy man is?', options: ['Oba', 'Chief', 'Obi', 'Alhaji'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'ke3079', question: 'Aso-Oke is a hand-woven fabric from which group?', options: ['Igbo', 'Yoruba', 'Hausa', 'Fulani'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3080', question: 'The New Yam Festival is celebrated by which group?', options: ['Yoruba', 'Hausa', 'Fulani', 'Igbo'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3081', question: 'Nigeria\'s Independence Day is?', options: ['June 12', 'October 1', 'September 1', 'January 1'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3082', question: 'Democracy Day in Nigeria is celebrated on?', options: ['October 1', 'January 15', 'May 29', 'June 12'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3083', question: 'The Nigerian coat of arms features which animals?', options: ['Lions', 'Leopards', 'Horses', 'Eagles'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3084', question: 'Nigeria\'s motto is?', options: ['Unity is Strength', 'One Nigeria', 'Unity and Faith, Peace and Progress', 'Together We Stand'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3085', question: 'The green in Nigeria\'s flag represents?', options: ['Water', 'Peace', 'Hope', 'Agriculture/forests'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3086', question: 'The white in Nigeria\'s flag represents?', options: ['Peace and unity', 'Clouds', 'Snow', 'Purity'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3087', question: 'Which Nigerian author wrote "Things Fall Apart"?', options: ['Chinua Achebe', 'Wole Soyinka', 'Ben Okri', 'Chimamanda Adichie'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3088', question: 'Wole Soyinka won the Nobel Prize in which year?', options: ['1986', '1984', '1988', '1990'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'ke3089', question: 'Fela Kuti created which music genre?', options: ['Afrobeat', 'Juju', 'Highlife', 'Fuji'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3090', question: 'King Sunny Ade is associated with which music?', options: ['Afrobeat', 'Fuji', 'Juju music', 'Apala'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3091', question: 'The Benin Bronzes were taken by which colonial power?', options: ['France', 'Germany', 'Portugal', 'Britain'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'kh3092', question: 'Igbo-Ukwu archaeological finds date to which century?', options: ['5th', '13th', '9th', '17th'], correctAnswer: 2, category: 'knowledge', difficulty: 'hard' },
  { id: 'km3093', question: 'The Ife terracotta and bronze heads are from which kingdom?', options: ['Benin', 'Ile-Ife', 'Oyo', 'Nupe'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3094', question: 'Which Nigerian ethnic group has the Atilogwu dance?', options: ['Igbo', 'Yoruba', 'Hausa', 'Ijaw'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'kh3095', question: 'The Sharo/Shadi festival involves what test?', options: ['Dancing', 'Wrestling', 'Flogging endurance', 'Singing'], correctAnswer: 2, category: 'knowledge', difficulty: 'hard' },
  { id: 'ke3096', question: 'Nigeria\'s national football team is called?', options: ['Black Stars', 'Harambee Stars', 'Indomitable Lions', 'Super Eagles'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3097', question: 'Which Nigerian won the Olympic gold in 1996 football?', options: ['Jay-Jay Okocha', ',', ',', 'The team (Atlanta'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'kh3098', question: 'Which Nigerian footballer scored the fastest World Cup goal?', options: ['Samaila Aminu', 'Okocha', 'Rashidi Yekini', 'Kanu'], correctAnswer: 0, category: 'knowledge', difficulty: 'hard' },
  { id: 'ke3099', question: 'The women\'s national football team is called?', options: ['Super Eagles', 'Green Eagles', 'Super Falcons', 'Lady Eagles'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3100', question: 'Which stadium hosted the 2003 All Africa Games?', options: ['National Stadium Lagos', 'Abuja National Stadium', 'MKO Abiola Stadium', 'Teslim Balogun Stadium'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'kh3101', question: 'Nigeria first participated in the Olympics in which year?', options: ['1948', '1964', '1960', '1952'], correctAnswer: 3, category: 'knowledge', difficulty: 'hard' },
  { id: 'kh3102', question: 'Which Nigerian boxer became world heavyweight champion?', options: ['None', 'Anthony Joshua', 'David Izonritei', 'Samuel Peter'], correctAnswer: 3, category: 'knowledge', difficulty: 'hard' },
  { id: 'km3103', question: 'The Nigerian Premier Football League has how many teams?', options: ['20', '18', '16', '22'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'kh3104', question: 'Which Nigerian sprinter won Olympic gold?', options: ['Chioma Ajunwa', 'Mary Onyali', 'Blessing Okagbare', 'Falilat Ogunkoya'], correctAnswer: 0, category: 'knowledge', difficulty: 'hard' },
  { id: 'km3105', question: 'Chioma Ajunwa won gold in which event?', options: ['100m sprint', 'Long jump', '400m', 'High jump'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3106', question: 'Nigeria\'s currency code is?', options: ['NGR', 'NGA', 'NGN', 'NIG'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'ke3107', question: 'The highest denomination Nigerian note is?', options: ['\u20a6500', '\u20a65000', '\u20a61000', '\u20a6200'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'kh3108', question: 'The Central Bank of Nigeria was established in?', options: ['1952', '1963', '1960', '1958'], correctAnswer: 3, category: 'knowledge', difficulty: 'hard' },
  { id: 'kh3109', question: 'Which sector contributes most to Nigeria\'s GDP?', options: ['Oil', 'Agriculture', 'Manufacturing', 'Services'], correctAnswer: 3, category: 'knowledge', difficulty: 'hard' },
  { id: 'ke3110', question: 'Nigeria is the largest economy in?', options: ['The world', 'Africa', 'West Africa only', 'Sub-Saharan Africa'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3111', question: 'The Nigerian naira symbol is?', options: ['N', '$', '\u20a6', '\u00a3'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3112', question: 'Which crop was Nigeria\'s main export before oil?', options: ['Rubber', 'Cocoa/Groundnuts', 'Cotton', 'Timber'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'kh3113', question: 'The Nigerian Economic Summit Group (NESG) was founded in?', options: ['1988', '1993', '1996', '2000'], correctAnswer: 2, category: 'knowledge', difficulty: 'hard' },
  { id: 'kh3114', question: 'Nigeria\'s main trading partner is?', options: ['USA', 'China', 'India', 'UK'], correctAnswer: 2, category: 'knowledge', difficulty: 'hard' },
  { id: 'km3115', question: 'The Dangote Refinery is located in which state?', options: ['Rivers', 'Ogun', 'Delta', 'Lagos'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'ke3116', question: 'What is the capital of Abia State?', options: ['Yola', 'Umuahia', 'Uyo', 'Awka'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3117', question: 'What is the capital of Adamawa State?', options: ['Yola', 'Umuahia', 'Awka', 'Uyo'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3118', question: 'What is the capital of Akwa Ibom State?', options: ['Yola', 'Umuahia', 'Awka', 'Uyo'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3119', question: 'What is the capital of Anambra State?', options: ['Uyo', 'Awka', 'Yola', 'Umuahia'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3120', question: 'What is the capital of Bauchi State?', options: ['Bauchi', 'Umuahia', 'Yola', 'Uyo'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3121', question: 'What is the capital of Bayelsa State?', options: ['Yenagoa', 'Yola', 'Umuahia', 'Uyo'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3122', question: 'What is the capital of Benue State?', options: ['Makurdi', 'Uyo', 'Umuahia', 'Yola'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3123', question: 'What is the capital of Borno State?', options: ['Maiduguri', 'Umuahia', 'Yola', 'Uyo'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3124', question: 'What is the capital of Cross River State?', options: ['Calabar', 'Umuahia', 'Uyo', 'Yola'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3125', question: 'What is the capital of Delta State?', options: ['Asaba', 'Uyo', 'Yola', 'Umuahia'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3126', question: 'What is the capital of Ebonyi State?', options: ['Yola', 'Uyo', 'Abakaliki', 'Umuahia'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3127', question: 'What is the capital of Edo State?', options: ['Yola', 'Uyo', 'Benin City', 'Umuahia'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3128', question: 'What is the capital of Ekiti State?', options: ['Uyo', 'Yola', 'Umuahia', 'Ado-Ekiti'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3129', question: 'What is the capital of Enugu State?', options: ['Yola', 'Uyo', 'Enugu', 'Umuahia'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3130', question: 'What is the capital of Gombe State?', options: ['Uyo', 'Gombe', 'Umuahia', 'Yola'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3131', question: 'What is the capital of Imo State?', options: ['Umuahia', 'Yola', 'Uyo', 'Owerri'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3132', question: 'What is the capital of Jigawa State?', options: ['Yola', 'Uyo', 'Umuahia', 'Dutse'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3133', question: 'What is the capital of Kaduna State?', options: ['Umuahia', 'Uyo', 'Yola', 'Kaduna'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3134', question: 'What is the capital of Kano State?', options: ['Uyo', 'Yola', 'Umuahia', 'Kano'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3135', question: 'What is the capital of Katsina State?', options: ['Umuahia', 'Yola', 'Uyo', 'Katsina'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3136', question: 'What is the capital of Kebbi State?', options: ['Umuahia', 'Uyo', 'Yola', 'Birnin Kebbi'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3137', question: 'What is the capital of Kogi State?', options: ['Uyo', 'Lokoja', 'Umuahia', 'Yola'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3138', question: 'What is the capital of Kwara State?', options: ['Umuahia', 'Uyo', 'Ilorin', 'Yola'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3139', question: 'What is the capital of Lagos State?', options: ['Ikeja', 'Uyo', 'Umuahia', 'Yola'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3140', question: 'What is the capital of Nassarawa State?', options: ['Yola', 'Lafia', 'Uyo', 'Umuahia'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3141', question: 'What is the capital of Niger State?', options: ['Minna', 'Umuahia', 'Yola', 'Uyo'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3142', question: 'What is the capital of Ogun State?', options: ['Umuahia', 'Abeokuta', 'Yola', 'Uyo'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3143', question: 'What is the capital of Ondo State?', options: ['Umuahia', 'Akure', 'Uyo', 'Yola'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3144', question: 'What is the capital of Osun State?', options: ['Yola', 'Uyo', 'Umuahia', 'Osogbo'], correctAnswer: 3, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3145', question: 'What is the capital of Oyo State?', options: ['Umuahia', 'Uyo', 'Ibadan', 'Yola'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3146', question: 'What is the capital of Plateau State?', options: ['Uyo', 'Jos', 'Yola', 'Umuahia'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3147', question: 'What is the capital of Rivers State?', options: ['Port Harcourt', 'Umuahia', 'Uyo', 'Yola'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3148', question: 'What is the capital of Sokoto State?', options: ['Sokoto', 'Umuahia', 'Uyo', 'Yola'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3149', question: 'What is the capital of Taraba State?', options: ['Umuahia', 'Jalingo', 'Yola', 'Uyo'], correctAnswer: 1, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3150', question: 'What is the capital of Yobe State?', options: ['Damaturu', 'Umuahia', 'Uyo', 'Yola'], correctAnswer: 0, category: 'knowledge', difficulty: 'easy' },
  { id: 'ke3151', question: 'What is the capital of Zamfara State?', options: ['Uyo', 'Yola', 'Gusau', 'Umuahia'], correctAnswer: 2, category: 'knowledge', difficulty: 'easy' },
  { id: 'km3152', question: 'What is the slogan of Lagos State?', options: ['Gateway State', 'Pacesetter State', 'State of the Living Spring', 'Centre of Excellence'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3153', question: 'What is the slogan of Ogun State?', options: ['State of the Living Spring', 'Pacesetter State', 'Gateway State', 'Centre of Excellence'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3154', question: 'What is the slogan of Oyo State?', options: ['Gateway State', 'State of the Living Spring', 'Centre of Excellence', 'Pacesetter State'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3155', question: 'What is the slogan of Osun State?', options: ['State of the Living Spring', 'Gateway State', 'Pacesetter State', 'Centre of Excellence'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3156', question: 'What is the slogan of Ondo State?', options: ['Pacesetter State', 'Centre of Excellence', 'Sunshine State', 'Gateway State'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3157', question: 'What is the slogan of Ekiti State?', options: ['Gateway State', 'Centre of Excellence', 'Fountain of Knowledge', 'Pacesetter State'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3158', question: 'What is the slogan of Kano State?', options: ['Centre of Excellence', 'Pacesetter State', 'Centre of Commerce', 'Gateway State'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3159', question: 'What is the slogan of Kaduna State?', options: ['Centre of Excellence', 'Gateway State', 'Centre of Learning', 'Pacesetter State'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3160', question: 'What is the slogan of Benue State?', options: ['Food Basket of the Nation', 'Pacesetter State', 'Centre of Excellence', 'Gateway State'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3161', question: 'What is the slogan of Plateau State?', options: ['Home of Peace and Tourism', 'Centre of Excellence', 'Gateway State', 'Pacesetter State'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3162', question: 'What is the slogan of Rivers State?', options: ['Pacesetter State', 'Centre of Excellence', 'Treasure Base of the Nation', 'Gateway State'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3163', question: 'What is the slogan of Delta State?', options: ['The Big Heart', 'Centre of Excellence', 'Gateway State', 'Pacesetter State'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3164', question: 'What is the slogan of Edo State?', options: ['Gateway State', 'Heartbeat of the Nation', 'Pacesetter State', 'Centre of Excellence'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3165', question: 'What is the slogan of Cross River State?', options: ['Pacesetter State', 'Gateway State', 'The People', 'Centre of Excellence'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3166', question: 'What is the slogan of Akwa Ibom State?', options: ['Land of Promise', 'Gateway State', 'Pacesetter State', 'Centre of Excellence'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3167', question: 'What is the slogan of Bayelsa State?', options: ['Pacesetter State', 'Glory of All Lands', 'Gateway State', 'Centre of Excellence'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3168', question: 'What is the slogan of Enugu State?', options: ['Centre of Excellence', 'Gateway State', 'Coal City State', 'Pacesetter State'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3169', question: 'What is the slogan of Anambra State?', options: ['Light of the Nation', 'Pacesetter State', 'Centre of Excellence', 'Gateway State'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3170', question: 'What is the slogan of Imo State?', options: ['Centre of Excellence', 'Eastern Heartland', 'Gateway State', 'Pacesetter State'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3171', question: 'What is the slogan of Abia State?', options: ['Pacesetter State', 'Gateway State', 'Centre of Excellence', 'God'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3172', question: 'What is the slogan of Ebonyi State?', options: ['Salt of the Nation', 'Gateway State', 'Centre of Excellence', 'Pacesetter State'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3173', question: 'What is the slogan of Kogi State?', options: ['The Confluence State', 'Centre of Excellence', 'Pacesetter State', 'Gateway State'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3174', question: 'What is the slogan of Kwara State?', options: ['State of Harmony', 'Gateway State', 'Pacesetter State', 'Centre of Excellence'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3175', question: 'What is the slogan of Niger State?', options: ['Gateway State', 'Centre of Excellence', 'Pacesetter State', 'The Power State'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3176', question: 'What is the slogan of Nassarawa State?', options: ['Gateway State', 'Pacesetter State', 'Centre of Excellence', 'Home of Solid Minerals'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3177', question: 'What is the slogan of Adamawa State?', options: ['Pacesetter State', 'Land of Beauty', 'Gateway State', 'Centre of Excellence'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3178', question: 'What is the slogan of Taraba State?', options: ['Gateway State', 'Centre of Excellence', 'Nature', 'Pacesetter State'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3179', question: 'What is the slogan of Bauchi State?', options: ['Gateway State', 'Centre of Excellence', 'Pacesetter State', 'Pearl of Tourism'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3180', question: 'What is the slogan of Gombe State?', options: ['Pacesetter State', 'Jewel in the Savannah', 'Gateway State', 'Centre of Excellence'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3181', question: 'What is the slogan of Borno State?', options: ['Pacesetter State', 'Home of Peace', 'Gateway State', 'Centre of Excellence'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3182', question: 'What is the slogan of Yobe State?', options: ['Gateway State', 'Pride of the Sahel', 'Centre of Excellence', 'Pacesetter State'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3183', question: 'What is the slogan of Jigawa State?', options: ['Pacesetter State', 'The New World', 'Centre of Excellence', 'Gateway State'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3184', question: 'What is the slogan of Katsina State?', options: ['Home of Hospitality', 'Gateway State', 'Pacesetter State', 'Centre of Excellence'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3185', question: 'What is the slogan of Kebbi State?', options: ['Gateway State', 'Pacesetter State', 'Land of Equity', 'Centre of Excellence'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3186', question: 'What is the slogan of Sokoto State?', options: ['Gateway State', 'Centre of Excellence', 'Pacesetter State', 'Seat of the Caliphate'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3187', question: 'What is the slogan of Zamfara State?', options: ['Centre of Excellence', 'Gateway State', 'Farming is Our Pride', 'Pacesetter State'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3188', question: 'Which state has the slogan \"Centre of Excellence\"?', options: ['Oyo', 'Lagos', 'Osun', 'Ogun'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3189', question: 'Which state has the slogan \"Gateway State\"?', options: ['Ogun', 'Oyo', 'Osun', 'Lagos'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3190', question: 'Which state has the slogan \"Pacesetter State\"?', options: ['Oyo', 'Lagos', 'Osun', 'Ogun'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3191', question: 'Which state has the slogan \"State of the Living Spring\"?', options: ['Ogun', 'Oyo', 'Osun', 'Lagos'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3192', question: 'Which state has the slogan \"Sunshine State\"?', options: ['Ondo', 'Ogun', 'Lagos', 'Oyo'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3193', question: 'Which state has the slogan \"Fountain of Knowledge\"?', options: ['Lagos', 'Oyo', 'Ogun', 'Ekiti'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3194', question: 'Which state has the slogan \"Centre of Commerce\"?', options: ['Lagos', 'Oyo', 'Ogun', 'Kano'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3195', question: 'Which state has the slogan \"Centre of Learning\"?', options: ['Oyo', 'Kaduna', 'Lagos', 'Ogun'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3196', question: 'Which state has the slogan \"Food Basket of the Nation\"?', options: ['Ogun', 'Lagos', 'Oyo', 'Benue'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3197', question: 'Which state has the slogan \"Home of Peace and Tourism\"?', options: ['Ogun', 'Lagos', 'Oyo', 'Plateau'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3198', question: 'Which state has the slogan \"Treasure Base of the Nation\"?', options: ['Lagos', 'Rivers', 'Oyo', 'Ogun'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3199', question: 'Which state has the slogan \"The Big Heart\"?', options: ['Lagos', 'Delta', 'Oyo', 'Ogun'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3200', question: 'Which state has the slogan \"Heartbeat of the Nation\"?', options: ['Oyo', 'Lagos', 'Edo', 'Ogun'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3201', question: 'Which state has the slogan \"The People\'s Paradise\"?', options: ['Ogun', 'Cross River', 'Oyo', 'Lagos'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3202', question: 'Which state has the slogan \"Land of Promise\"?', options: ['Lagos', 'Oyo', 'Akwa Ibom', 'Ogun'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3203', question: 'Which state has the slogan \"Glory of All Lands\"?', options: ['Oyo', 'Bayelsa', 'Lagos', 'Ogun'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3204', question: 'Which state has the slogan \"Coal City State\"?', options: ['Ogun', 'Oyo', 'Lagos', 'Enugu'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3205', question: 'Which state has the slogan \"Light of the Nation\"?', options: ['Ogun', 'Oyo', 'Lagos', 'Anambra'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3206', question: 'Which state has the slogan \"Eastern Heartland\"?', options: ['Lagos', 'Oyo', 'Imo', 'Ogun'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3207', question: 'Which state has the slogan \"God\'s Own State\"?', options: ['Abia', 'Oyo', 'Lagos', 'Ogun'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3208', question: 'Which state has the slogan \"Salt of the Nation\"?', options: ['Ebonyi', 'Ogun', 'Oyo', 'Lagos'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3209', question: 'Which state has the slogan \"The Confluence State\"?', options: ['Ogun', 'Kogi', 'Lagos', 'Oyo'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3210', question: 'Which state has the slogan \"State of Harmony\"?', options: ['Kwara', 'Oyo', 'Lagos', 'Ogun'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3211', question: 'Which state has the slogan \"The Power State\"?', options: ['Oyo', 'Niger', 'Lagos', 'Ogun'], correctAnswer: 1, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3212', question: 'Which state has the slogan \"Home of Solid Minerals\"?', options: ['Lagos', 'Ogun', 'Oyo', 'Nassarawa'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3213', question: 'Which state has the slogan \"Land of Beauty\"?', options: ['Ogun', 'Oyo', 'Lagos', 'Adamawa'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3214', question: 'Which state has the slogan \"Nature\'s Gift to the Nation\"?', options: ['Ogun', 'Oyo', 'Lagos', 'Taraba'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3215', question: 'Which state has the slogan \"Pearl of Tourism\"?', options: ['Bauchi', 'Oyo', 'Lagos', 'Ogun'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3216', question: 'Which state has the slogan \"Jewel in the Savannah\"?', options: ['Oyo', 'Lagos', 'Gombe', 'Ogun'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3217', question: 'Which state has the slogan \"Home of Peace\"?', options: ['Ogun', 'Lagos', 'Borno', 'Oyo'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3218', question: 'Which state has the slogan \"Pride of the Sahel\"?', options: ['Yobe', 'Lagos', 'Oyo', 'Ogun'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3219', question: 'Which state has the slogan \"The New World\"?', options: ['Ogun', 'Oyo', 'Lagos', 'Jigawa'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3220', question: 'Which state has the slogan \"Home of Hospitality\"?', options: ['Katsina', 'Oyo', 'Lagos', 'Ogun'], correctAnswer: 0, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3221', question: 'Which state has the slogan \"Land of Equity\"?', options: ['Ogun', 'Oyo', 'Kebbi', 'Lagos'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3222', question: 'Which state has the slogan \"Seat of the Caliphate\"?', options: ['Lagos', 'Oyo', 'Sokoto', 'Ogun'], correctAnswer: 2, category: 'knowledge', difficulty: 'medium' },
  { id: 'km3223', question: 'Which state has the slogan \"Farming is Our Pride\"?', options: ['Oyo', 'Lagos', 'Ogun', 'Zamfara'], correctAnswer: 3, category: 'knowledge', difficulty: 'medium' },
];

export const extraRoadQuestions2: QuizQuestion[] = [
];
