import { useState } from 'react';
import { FileText, Plus, Download, Printer, Share2, MessageCircle, Mail, Copy, Smartphone } from 'lucide-react';
import { toast } from 'sonner';

interface Rider {
  id: string;
  rider_name: string;
}

interface InvoiceItem {
  description: string;
  qty: number;
  rate: number;
}

interface Invoice {
  id: string;
  invoiceNo: string;
  customerName: string;
  customerPhone: string;
  riderName: string;
  items: InvoiceItem[];
  total: number;
  date: string;
  status: 'draft' | 'sent' | 'paid';
}

export default function InvoiceGenerator({
  riders,
  businessName,
  storageKey = 'biz_invoices',
  title = 'Invoice Generator',
}: { riders: Rider[]; businessName: string; storageKey?: string; title?: string }) {
  const [invoices, setInvoices] = useState<Invoice[]>(() => {
    try { return JSON.parse(localStorage.getItem(storageKey) || '[]'); } catch { return []; }
  });
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({
    customerName: '', customerPhone: '', riderId: '',
    items: [{ description: 'Delivery Service', qty: 1, rate: 500 }] as InvoiceItem[],
  });
  const [previewInvoice, setPreviewInvoice] = useState<Invoice | null>(null);

  const save = (updated: Invoice[]) => {
    setInvoices(updated);
    localStorage.setItem(storageKey, JSON.stringify(updated));
  };

  const addItem = () => setForm({ ...form, items: [...form.items, { description: '', qty: 1, rate: 0 }] });
  const updateItem = (i: number, field: keyof InvoiceItem, value: string | number) => {
    const items = [...form.items];
    (items[i] as any)[field] = value;
    setForm({ ...form, items });
  };
  const removeItem = (i: number) => setForm({ ...form, items: form.items.filter((_, idx) => idx !== i) });

  const createInvoice = (e: React.FormEvent) => {
    e.preventDefault();
    const rider = riders.find(r => r.id === form.riderId);
    const total = form.items.reduce((s, it) => s + it.qty * it.rate, 0);
    const inv: Invoice = {
      id: crypto.randomUUID(),
      invoiceNo: `INV-${Date.now().toString(36).toUpperCase()}`,
      customerName: form.customerName,
      customerPhone: form.customerPhone,
      riderName: rider?.rider_name || 'N/A',
      items: form.items,
      total,
      date: new Date().toISOString().split('T')[0],
      status: 'draft',
    };
    save([inv, ...invoices]);
    setForm({ customerName: '', customerPhone: '', riderId: '', items: [{ description: 'Delivery Service', qty: 1, rate: 500 }] });
    setShowForm(false);
    setPreviewInvoice(inv);
  };

  const markPaid = (id: string) => save(invoices.map(inv => inv.id === id ? { ...inv, status: 'paid' as const } : inv));

  const printInvoice = (inv: Invoice) => {
    const esc = (s: unknown) => String(s ?? '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
    const html = `
      <html><head><title>Invoice ${esc(inv.invoiceNo)}</title>
      <style>body{font-family:sans-serif;padding:30px;max-width:600px;margin:auto}
      h1{color:#1a1a1a;font-size:24px}table{width:100%;border-collapse:collapse;margin:20px 0}
      th,td{border-bottom:1px solid #eee;padding:8px;text-align:left}th{background:#f5f5f5}
      .total{font-size:18px;font-weight:bold;text-align:right;margin-top:20px}
      .header{display:flex;justify-content:space-between;align-items:flex-start}
      </style></head><body>
      <div class="header"><div><h1>${esc(businessName || 'Business')}</h1><p>Invoice: ${esc(inv.invoiceNo)}</p><p>Date: ${esc(inv.date)}</p></div></div>
      <hr/><p><strong>Customer:</strong> ${esc(inv.customerName)}</p><p><strong>Phone:</strong> ${esc(inv.customerPhone)}</p>
      <p><strong>Rider:</strong> ${esc(inv.riderName)}</p>
      <table><thead><tr><th>Description</th><th>Qty</th><th>Rate (₦)</th><th>Amount (₦)</th></tr></thead><tbody>
      ${inv.items.map(it => `<tr><td>${esc(it.description)}</td><td>${esc(it.qty)}</td><td>${esc(it.rate.toLocaleString())}</td><td>${esc((it.qty * it.rate).toLocaleString())}</td></tr>`).join('')}
      </tbody></table><p class="total">Total: ₦${inv.total.toLocaleString()}</p>
      <p style="color:#888;font-size:12px;margin-top:40px">Generated by Loca8tor</p>
      </body></html>`;
    const w = window.open('', '_blank');
    if (w) { w.document.write(html); w.document.close(); w.print(); }
  };

  const buildInvoiceSummary = (inv: Invoice) => {
    const lines = inv.items.map(it => `• ${it.description} × ${it.qty} @ ₦${it.rate.toLocaleString()} = ₦${(it.qty * it.rate).toLocaleString()}`).join('\n');
    return `Invoice ${inv.invoiceNo}\nFrom: ${businessName || 'Business'}\nDate: ${inv.date}\n\nItems:\n${lines}\n\nTotal: ₦${inv.total.toLocaleString()}`;
  };

  const shareWhatsApp = (inv: Invoice) => {
    const phone = (inv.customerPhone || '').replace(/[^0-9]/g, '');
    const text = encodeURIComponent(buildInvoiceSummary(inv));
    const url = phone
      ? `https://wa.me/${phone.startsWith('0') ? '234' + phone.slice(1) : phone}?text=${text}`
      : `https://wa.me/?text=${text}`;
    window.open(url, '_blank');
  };

  const shareEmail = (inv: Invoice) => {
    const subject = encodeURIComponent(`Invoice ${inv.invoiceNo} from ${businessName || 'Business'}`);
    const body = encodeURIComponent(buildInvoiceSummary(inv));
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  const shareSms = (inv: Invoice) => {
    const phone = (inv.customerPhone || '').replace(/[^0-9+]/g, '');
    const body = encodeURIComponent(buildInvoiceSummary(inv));
    window.location.href = `sms:${phone}?&body=${body}`;
  };

  const copyInvoice = async (inv: Invoice) => {
    try {
      await navigator.clipboard.writeText(buildInvoiceSummary(inv));
      toast.success('Invoice copied to clipboard');
    } catch {
      toast.error('Could not copy');
    }
  };

  const shareNative = async (inv: Invoice) => {
    const text = buildInvoiceSummary(inv);
    if ((navigator as any).share) {
      try { await (navigator as any).share({ title: inv.invoiceNo, text }); return; } catch {}
    }
    copyInvoice(inv);
  };

  return (
    <div className="bg-card rounded-lg ring-1 ring-border p-4 space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-sm font-heading font-bold text-foreground flex items-center gap-2">
          <FileText className="w-4 h-4 text-primary" /> {title}
        </p>
        <button onClick={() => { setShowForm(!showForm); setPreviewInvoice(null); }}
          className="flex items-center gap-1 text-xs text-primary font-medium hover:underline">
          <Plus className="w-3.5 h-3.5" /> New Invoice
        </button>
      </div>

      {showForm && (
        <form onSubmit={createInvoice} className="bg-secondary/60 rounded-lg p-3 space-y-2">
          <div className="grid grid-cols-2 gap-2">
            <input required value={form.customerName} onChange={e => setForm({ ...form, customerName: e.target.value })}
              placeholder="Customer name" className="rounded-md border border-input bg-background px-3 py-2 text-sm" />
            <input required value={form.customerPhone} onChange={e => setForm({ ...form, customerPhone: e.target.value })}
              placeholder="Customer phone" className="rounded-md border border-input bg-background px-3 py-2 text-sm" />
          </div>
          <select value={form.riderId} onChange={e => setForm({ ...form, riderId: e.target.value })}
            className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm">
            <option value="">Assign rider (optional)</option>
            {riders.map(r => <option key={r.id} value={r.id}>{r.rider_name}</option>)}
          </select>

          {/* Items */}
          <div className="space-y-1.5">
            <p className="text-[10px] font-medium text-foreground">Line Items</p>
            {form.items.map((it, i) => (
              <div key={i} className="grid grid-cols-[1fr_50px_70px_20px] gap-1 items-center">
                <input value={it.description} onChange={e => updateItem(i, 'description', e.target.value)}
                  placeholder="Description" className="rounded border border-input bg-background px-2 py-1.5 text-xs" />
                <input type="number" min={1} value={it.qty} onChange={e => updateItem(i, 'qty', +e.target.value)}
                  className="rounded border border-input bg-background px-2 py-1.5 text-xs" />
                <input type="number" min={0} value={it.rate} onChange={e => updateItem(i, 'rate', +e.target.value)}
                  placeholder="₦" className="rounded border border-input bg-background px-2 py-1.5 text-xs" />
                {form.items.length > 1 && (
                  <button type="button" onClick={() => removeItem(i)} className="text-destructive text-xs">×</button>
                )}
              </div>
            ))}
            <button type="button" onClick={addItem} className="text-[10px] text-primary font-medium hover:underline">+ Add line</button>
          </div>

          <div className="flex items-center justify-between bg-background rounded-lg px-3 py-2">
            <span className="text-sm font-bold text-foreground">Total</span>
            <span className="text-sm font-bold text-primary">₦{form.items.reduce((s, it) => s + it.qty * it.rate, 0).toLocaleString()}</span>
          </div>

          <button type="submit" className="w-full bg-primary text-primary-foreground text-xs font-semibold py-2 rounded-lg">
            Create Invoice
          </button>
        </form>
      )}

      {/* Preview */}
      {previewInvoice && (
        <div className="bg-primary/5 rounded-lg p-4 space-y-3">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-bold text-foreground">{previewInvoice.invoiceNo}</p>
              <p className="text-[10px] text-muted-foreground">{previewInvoice.date}</p>
            </div>
            <button onClick={() => printInvoice(previewInvoice)}
              className="flex items-center gap-1 text-xs text-primary font-medium hover:underline">
              <Printer className="w-3 h-3" /> Print
            </button>
          </div>
          <p className="text-xs text-foreground">Customer: {previewInvoice.customerName} · {previewInvoice.customerPhone}</p>
          <p className="text-xs font-bold text-primary">Total: ₦{previewInvoice.total.toLocaleString()}</p>
          <div className="flex flex-wrap gap-2 pt-2 border-t border-primary/10">
            <button onClick={() => shareWhatsApp(previewInvoice)}
              className="flex items-center gap-1 text-[11px] font-semibold px-2.5 py-1.5 rounded-md bg-[#25D366]/15 text-[#128C7E] hover:bg-[#25D366]/25">
              <MessageCircle className="w-3 h-3" /> WhatsApp
            </button>
            <button onClick={() => shareEmail(previewInvoice)}
              className="flex items-center gap-1 text-[11px] font-semibold px-2.5 py-1.5 rounded-md bg-secondary hover:bg-secondary/70">
              <Mail className="w-3 h-3" /> Email
            </button>
            <button onClick={() => shareSms(previewInvoice)}
              className="flex items-center gap-1 text-[11px] font-semibold px-2.5 py-1.5 rounded-md bg-secondary hover:bg-secondary/70">
              <Smartphone className="w-3 h-3" /> Text (SMS)
            </button>
            <button onClick={() => copyInvoice(previewInvoice)}
              className="flex items-center gap-1 text-[11px] font-semibold px-2.5 py-1.5 rounded-md bg-secondary hover:bg-secondary/70">
              <Copy className="w-3 h-3" /> Copy
            </button>
            <button onClick={() => shareNative(previewInvoice)}
              className="flex items-center gap-1 text-[11px] font-semibold px-2.5 py-1.5 rounded-md bg-secondary hover:bg-secondary/70">
              <Share2 className="w-3 h-3" /> Share…
            </button>
          </div>
        </div>
      )}

      {/* List */}
      {invoices.length > 0 && !showForm && (
        <div className="space-y-1.5">
          <p className="text-xs font-medium text-foreground">Recent Invoices ({invoices.length})</p>
          {invoices.slice(0, 10).map(inv => (
            <div key={inv.id} className="flex items-center justify-between bg-secondary/40 rounded-lg px-3 py-2 cursor-pointer hover:bg-secondary/60"
              onClick={() => setPreviewInvoice(inv)}>
              <div>
                <p className="text-xs font-medium text-foreground">{inv.invoiceNo} · {inv.customerName}</p>
                <p className="text-[10px] text-muted-foreground">{inv.date} · {inv.riderName}</p>
              </div>
              <div className="text-right">
                <p className="text-xs font-bold text-foreground">₦{inv.total.toLocaleString()}</p>
                <span className={`text-[9px] font-medium px-1.5 py-0.5 rounded-full ${inv.status === 'paid' ? 'bg-green-100 text-green-700' : inv.status === 'sent' ? 'bg-blue-100 text-blue-700' : 'bg-yellow-100 text-yellow-700'}`}>
                  {inv.status}
                </span>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
